version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  martin-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - GROK3_API_KEY=${GROK3_API_KEY}
      - ENVIRONMENT=development
    depends_on:
      - redis
    volumes:
      - .:/app
    command: python martin_backend.py

volumes:
  redis_data:
